int bitAnd(int, int);
int test_bitAnd(int, int);
int bitXor(int, int);
int test_bitXor(int, int);
int thirdBits();
int test_thirdBits();
int fitsBits(int, int);
int test_fitsBits(int, int);
int sign(int);
int test_sign(int);
int getByte(int, int);
int test_getByte(int, int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int addOK(int, int);
int test_addOK(int, int);
int bang(int);
int test_bang(int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int isPower2(int);
int test_isPower2(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
unsigned float_twice(unsigned);
unsigned test_float_twice(unsigned);
