#include "bitNor.c"
#include "copyLSB.c"
#include "isEqual.c"
#include "bitMask.c"
#include "bitCount.c"
#include "tmax.c"
#include "isNonNegative.c"
#include "addOK.c"
#include "rempwr2.c"
#include "isLess.c"
#include "absVal.c"
#include "isPower2.c"
#include "float_neg.c"
#include "float_half.c"
#include "float_i2f.c"


