# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/huchao/Daily-Learning/Verilog/lab2/lab2_3/lab3_1_1/lab3_1_1.cache/wt [current_project]
set_property parent.project_path /home/huchao/Daily-Learning/Verilog/lab2/lab2_3/lab3_1_1/lab3_1_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/huchao/Daily-Learning/Verilog/lab2/lab2_3/lab3_1_1/lab3_1_1.srcs/sources_1/new/decoder_3to8_dataflow.v
synth_design -top decoder_3to8_dataflow -part xc7a100tcsg324-1
write_checkpoint -noxdef decoder_3to8_dataflow.dcp
catch { report_utilization -file decoder_3to8_dataflow_utilization_synth.rpt -pb decoder_3to8_dataflow_utilization_synth.pb }
