hehe1:
	gcc -Wall -Wextra -g lab1.c -o lab1

hehe2:
	gcc -Wall -Wextra -g lab2.c -lpthread -o lab2

hehe3:
	gcc -Wall -Wextra -g readbuf.c -o readbuf
	gcc -Wall -Wextra -g writebuf.c -o writebuf
	gcc -Wall -Wextra -g lab3.c -o lab3

hehe4:
	gcc -Wall -Wextra -g readbuf_1.1.c -o readbuf_1.1
	gcc -Wall -Wextra -g writebuf_1.1.c -o writebuf_1.1
	gcc -Wall -Wextra -g lab3_1.1.c -o lab3_1.1

hehe5:
	gcc -Wall -Wextra -g readbuf_1.2.c -o readbuf_1.2
	gcc -Wall -Wextra -g writebuf_1.2.c -o writebuf_1.2
	gcc -Wall -Wextra -g lab3_1.2.c -o lab3_1.2



hehet:
	gcc -Wall -Wextra -g test.c -lpthread -o test


.PHONY=run

rlab1:
	./lab1

rlab2:
	./lab2

rlab3:
	./lab3 test.c hehe.c
