hehe1:
	gcc -Wall -Wextra -g lab1.c -o lab1

hehe2:
	gcc -Wall -Wextra -g lab2.c -lpthread -o lab2

hehe3:
	gcc -Wall -Wextra -g lab3.c -o lab3

hehet:
	gcc -Wall -Wextra -g test.c -lpthread -o test


.PHONY=run

rlab1:
	./lab1

rlab2:
	./lab2
