;计算平均成绩
.386
.model flat, c
.code
public Ave
Ave	PROC
	MOV	ECX,4
	MOV	EDI,0
AVG:
	PUSH EBP
    MOV EBP,ESP
    MOV ESI,[EBP+8]
    POP EBP
	MOV	EBX,[ESI+EDI * 4]
	MOV	EAX,[ESI+EDI * 4+1 * 4]
	LEA	EAX,[EAX+EBX*2]
	MOV	EBX,[ESI+EDI * 4+2 * 4]
	LEA	EBX,[EBX+EAX*2]
	MOV	EAX,92492493H
	IMUL	EBX
	ADD	EDX,EBX
	SAR 	EDX,2
	MOV	EAX,EDX
	SHR	EAX,1FH
	ADD	EDX,EAX
	MOV	[ESI+EDI * 4+3 * 4],EDX
	ADD	EDI,4
	LOOP	AVG
	RET
Ave	ENDP
	END