INIT:	MOV	AX,DI
				MOV	BL,IN_NAME[1]
				SUB	AX,BX
				MOV	POIN,OFFSET BUF
				ADD	POIN,AX
				ADD	POIN,11
				MOV	CX,N
			;计算平均成绩
			AVG:	LEA	DI,BUF+10
				MOV	BL,BUF[DI]
				MOV	AL,BUF[DI+1]
				LEA	EAX,[EAX+EBX*2]
				MOV	BL,BUF[DI+2]
				LEA	ESI,[EBX+EAX*2]
				MOV	EAX,92492493H
				IMUL	ESI
				ADD	EDX,ESI
				SAR 	EDX,2
				MOV	EAX,EDX
				SHR	EAX,1FH
				ADD	EAX,EDX
				MOV	BUF[DI+3],AL
				ADD	DI,14
				LOOP	AVG
				DEC	COUNT
				JNZ	LOPA
				MOV	AX,1