EXTRN	F10T2:NEAR,F2T10:NEAR
.386
STACK	SEGMENT	USE16	STACK
	DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
NUMB	DW	35	DUP(0)
A 	DW	0
B 	DW	0
TIP1	DB	'Please enter the number:'
DATA	ENDS
CODE	SEGMENT	USE16
       	ASSUME	CS:CODE,DS:DATA,SS:STACK
START:  MOV 	AX,DATA
	MOV 	DS,AX
	LEA	BX,TIP1
	CALL	PLUS
	MOV	A,AX
	CALL	PLUS
	ADD	AX,A
	CALL	F2T10
CODE	ENDS
	END	START

PLUS	PROC
	MOV	DX,BX
	MOV	AH,9
	INT	21H
	LEA	DX,NUMB
	MOV	AH,10
	INT	21H
	LEA	SI,NUMB+2
	MOV	CS,NUMB+1
	MOV	DX,16
	CALL	F10T2
	RET
PLUS	ENDP