.386
.MODEL	FLAT,STDCALL
OPTION	CASEMAP:NONE
MessageBoxA	PROTO:DWORD,:DWORD,:DWORD,:DWORD
ExitProcess	PROTO:DWORD
INCLUDELIB	USER32.LIB
INCLUDELIB	KERNEL32.LIB
.DATA
	szDlgTitle	DB	'A WIN32 Sample:ADDER',0
	szMsg	DB	'00H+00H=00H',0
	A 	DB	1EH
	B 	DB	3AH
	MB_OK	EQU	0
.CODE
START:
	CALL	ADDER
	INVOKE	MessageBoxA,0, ADDR 	szMsg, ADDR 	szDlgTitle, MB_OK
	INVOKE	ExitProcess,0

ADDER	PROC 
	MOV	ESI,OFFSET	szMsg
	MOV	AL,A
	CALL	CONVERT
	ADD 	ESI,4
	MOV	AL,B
	CALL	CONVERT
	MOV	AL,A
	ADD	AL,B
	ADD 	ESI,4
	CALL	CONVERT
	RET
ADDER	ENDP

CONVERT	PROC
	MOV	AH,AL
	SHR	AL,4
	CMP 	AL,10
	JB	L1
	ADD 	AL,7
L1:	ADD 	AL,30H
	MOV	[ESI],AL
	AND	AH,0FH
	CMP 	AH,10
	JB	L2
	ADD 	AH,7
L2:	ADD 	AH,30H
	MOV	[ESI+1],AH
	RET
CONVERT	ENDP
	END 	START