# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/huchao/Daily-Learning/Verilog/lab2/lab2_4/lab4_1_1/lab4_1_1.cache/wt [current_project]
set_property parent.project_path /home/huchao/Daily-Learning/Verilog/lab2/lab2_4/lab4_1_1/lab4_1_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/huchao/Daily-Learning/Verilog/lab2/lab2_4/lab4_1_1/lab4_1_1.srcs/sources_1/new/add_two_values_task.v
synth_design -top add_two_values_task -part xc7a100tcsg324-1
write_checkpoint -noxdef add_two_values_task.dcp
catch { report_utilization -file add_two_values_task_utilization_synth.rpt -pb add_two_values_task_utilization_synth.pb }
