# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/huchao/Daily-Learning/Digital-Logic/lab/design/Decoder/Decoder.cache/wt [current_project]
set_property parent.project_path /home/huchao/Daily-Learning/Digital-Logic/lab/design/Decoder/Decoder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/huchao/Daily-Learning/Digital-Logic/lab/design/Decoder/Decoder.srcs/sources_1/new/Chip_Decoder.v
  /home/huchao/Daily-Learning/Digital-Logic/lab/design/Decoder/Decoder.srcs/sources_1/new/Paragraph_Decoder.v
  /home/huchao/Daily-Learning/Digital-Logic/lab/design/Decoder/Decoder.srcs/sources_1/new/Decoder.v
}
synth_design -top Decoder -part xc7a100tcsg324-1
write_checkpoint -noxdef Decoder.dcp
catch { report_utilization -file Decoder_utilization_synth.rpt -pb Decoder_utilization_synth.pb }
