function fig = window0()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load window0

h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','D:\MATLABR11\work\mysignal\window0.m', ...
	'MenuBar','none', ...
	'Name','信号与线性系统实验', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[0 0.01 1 0.96], ...
	'Resize','on', ...
   'Tag','Window0', ...
   'Units','normalized', ...
   'ToolBar','none');
h1 = axes('Parent',h0, ...
	'Units','normalized', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Position',[0 0 1 1], ...
	'Tag','Axes', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','signal showlist', ...
	'FontName','宋体', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'Position',[0.1 0.25 0.3 0.5], ...
	'Style','listbox', ...
	'Tag','MenuList', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9300000000000001 0.9300000000000001 0.9300000000000001], ...
	'Enable','inactive', ...
	'FontName','宋体', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'Max',2, ...
	'Position',[0.45 0.45 0.45 0.3], ...
	'Style','listbox', ...
	'Tag','AboutList', ...
	'UserData',mat6, ...
	'Value',[]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'Callback','close(gcf)', ...
	'FontName','隶书', ...
	'FontSize',16, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.1 0.2 0.05], ...
	'String','关 闭', ...
	'Tag','Close');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'FontName','隶书', ...
	'FontSize',16, ...
	'ListboxTop',0, ...
	'Position',[0.7 0.1 0.2 0.05], ...
	'String','确 定', ...
	'Tag','RunExpt');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontName','宋体', ...
	'FontSize',10, ...
	'HorizontalAlignment','left', ...
	'Position',[0.45 0.25 0.45 0.15], ...
	'Style','listbox', ...
	'Tag','RunList', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'FontName','隶书', ...
	'FontSize',16, ...
	'ListboxTop',0, ...
	'Position',[0.4 0.1 0.2 0.05], ...
	'String','帮 助', ...
   'Tag','RunHelp');

set(gcf,'defaultuicontrolfontsize',10);
set(gcf,'defaultuicontrolunits','normalized');
set(gcf,'defaultuicontrolhorizontal','left');
set(gcf,'defaultuicontrolFontUnits','normalized');


if nargout > 0, fig = h0; end

