# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/project_1/project_1.srcs/sources_1/new/jishuqi.v
synth_design -top jishuqi -part xc7a100tcsg324-1
write_checkpoint -noxdef jishuqi.dcp
catch { report_utilization -file jishuqi_utilization_synth.rpt -pb jishuqi_utilization_synth.pb }
