;程序名：six1
;作者：胡超
;功能：获取中断类型码10H对应的中断处理程序的入口地址
.386
STACK	SEGMENT	USE16	STACK
	DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
DATA	ENDS
CODE	SEGMENT	USE16
	ASSUME	CS:CODE,DS:DATA,SS:STACK
START:	
	MOV	AX,3510H	;方法二
	INT	21H
	MOV	AX,0		;方法三
	MOV	DS,AX
	MOV	AX,DS:[40H]
	MOV	AH,1
	INT	21H
	MOV	AH,4CH
	INT	21H
CODE	ENDS
	END	START