.386
STACK	SEGMENT	USE16	STACK
	DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
DATA	ENDS
CODE	SEGMENT	USE16
	ASSUME	CS:CODE,DS:DATA,SS:STACK
START:	
	MOV	AX,3510H
	INT	21H
	MOV	AX,0
	MOV	DS,AX
	MOV	AX,DS:[40H]
	MOV	AH,4CH
	INT	21H
CODE	ENDS
	END	START
